refactor. 브라우저에서는 node.js기반의 익스프레스 모듈을 인식하지 못함
TypeError: Cannot read property 'prototype' of undefined에 대한 수정
loginpage.js 에 require('express') 삭제

참고: https://www.inflearn.com/questions/30903